### ISSUE TITLE
missing "ignore" entry in bower.json

### ISSUE THREAD

**Issue by Maarten88** [paulmillr/console-polyfill#21]
This is a small issue, but it's easily fixed. 
My automated build script does a bower install which gives the following error:

    ##[error]bower console-polyfill#~0.2.1     invalid-meta console-polyfill is missing "ignore" entry in bower.json

I've set the build to continue on this error, and it works, however it now shows all my builds as "Partially succeeded". 

By adding the line 

    "ignore": [],

in bower.json, the warning should go away.

**Comment by paulmillr** [comment]
Fixed.

**Comment by Maarten88** [comment]
bower downloads from https://github.com/paulmillr/console-polyfill/archive/0.2.1.tar.gz, which still contains this issue. Could you put the fixed version there?

**Comment by paulmillr** [comment]
done?

**Comment by Maarten88** [comment]
Yes! Build is all green now, thanks!
