### ISSUE TITLE
Additional methods

### ISSUE THREAD

**Issue by micho** [paulmillr/console-polyfill#4]
This polyfill is missing some methods from the [console API](http://getfirebug.com/wiki/index.php/Console_API), like `console.table`.

If that's relevant, I can send a PR for it. I'm not sure if they've been left out intentionally.

**Comment by OZZlE** [comment]
@micho @paulmillr 6 years has passed, any update on this? will you be done soon? :D

**Comment by paulmillr** [comment]
Go ahead and make a pull request. Why are you asking me?

**Comment by OZZlE** [comment]
I solved it like this, what do you think? before I put time into a PR :) 

  window.console = typeof window.console !== 'object' || {};
  console.warn = typeof console.warn === 'function' || function () {
    return this;
  };
  console.log = typeof console.log === 'function' || function () {
    return this;
  };
  console.info = typeof console.info === 'function' || function () {
    return this;
  };
  console.error = typeof console.error === 'function' || function () {
    return this;
  };
  console.assert = typeof console.assert === 'function' || function () {
    return this;
  };
  console.dir = typeof console.dir === 'function' || function () {
    return this;
  };
  console.table = typeof console.table === 'function' || function () {
    return this;
  };
  console.group = typeof console.group === 'function' || function () {
    return this;
  };
  console.groupEnd = typeof console.groupEnd === 'function' || function () {
    return this;
  };
  console.time = typeof console.time === 'function' || function () {
    return this;
  };
  console.timeEnd = typeof console.timeEnd === 'function' || function () {
    return this;
  };
  console.timeLog = typeof console.timeLog === 'function' || function () {
    return this;
  };
  console.trace = typeof console.trace === 'function' || function () {
    return this;
  };
  console.clear = typeof console.clear === 'function' || function () {
    return this;
  };
  console.count = typeof console.count === 'function' || function () {
    return this;
  };
  console.debug = typeof console.debug === 'function' || function () {
    return this;
  };
  console.dirxml = typeof console.dirxml === 'function' || function () {
    return this;
  };
  console.groupCollapsed = typeof console.groupCollapsed === 'function' || function () {
    return this;
  };

**Comment by OZZlE** [comment]
https://github.com/paulmillr/console-polyfill/pull/28
