### ISSUE TITLE
FYI: Doesn't abstract console.log differences between IE & Chrome

### ISSUE THREAD

**Issue by jacobq** [paulmillr/console-polyfill#8]
In IE8 (and possibly newer versions as well), `typeof console.log` is `object` instead of `function`. I know there are other solutions that account for this and perhaps this one is not intended to do that, but it would be nice if it did so that it is safe to call a wrapper function like

```
function() {
    console.log.apply(console, arguments);
    /* (do something else here -- perhaps call cloud log aggregation API) */
}
```

**Comment by olivergeorge** [comment]
I think this would address a compatibility issue I'm having with IE8 and clojurescript

https://github.com/clojure/clojurescript/blob/4eebd45bd82f40c8e656d97ee996ed91c48a3ec5/src/cljs/cljs/core.cljs#L116

**Comment by adjohnson916** [comment]
+1
